# this is our github actions workflow for ci, using docker compose and sqlite
name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: set up docker compose
        run: docker compose up -d --build

      - name: create sqlite database file
        run: docker exec laravel-app touch /var/www/database/database.sqlite

      - name: run migrations
        run: docker exec laravel-app php artisan migrate --force

      - name: php lint
        run: docker exec laravel-app find . -type f -name '*.php' -exec php -l {} \;

      - name: run phpcs
        run: docker exec laravel-app vendor/bin/phpcs --standard=PSR12 app/ || true

      - name: run phpunit
        run: docker exec laravel-app php artisan test --coverage --min=70

      - name: security scan
        run: |
          docker exec laravel-app composer require --dev enlightn/security-checker
          docker exec laravel-app vendor/bin/security-checker security:check

      - name: tear down
        run: docker compose down --remove-orphans 